import type { Lesson } from './types'

export const mathLessons: Lesson[] = [
  {
    id: 'math-1',
    subjectId: 'math',
    title: 'Сложение до 10',
    titleKk: '10-ға дейін қосу',
    emoji: '➕',
    grade: [1],
    questions: [
      { kind: 'mc', prompt: '3 + 4 = ?', options: ['6', '7', '8', '9'], answer: '7' },
      { kind: 'mc', prompt: '5 + 2 = ?', options: ['6', '7', '8', '9'], answer: '7' },
      { kind: 'mc', prompt: '1 + 8 = ?', options: ['7', '8', '9', '10'], answer: '9' },
      { kind: 'mc', prompt: '4 + 4 = ?', options: ['6', '7', '8', '9'], answer: '8' },
      { kind: 'mc', prompt: '6 + 3 = ?', options: ['7', '8', '9', '10'], answer: '9' },
      { kind: 'mc', prompt: '2 + 5 = ?', options: ['5', '6', '7', '8'], answer: '7' },
      { kind: 'mc', prompt: '0 + 7 = ?', options: ['6', '7', '8', '9'], answer: '7' },
      { kind: 'mc', prompt: '3 + 6 = ?', options: ['7', '8', '9', '10'], answer: '9' },
    ],
  },
  {
    id: 'math-2',
    subjectId: 'math',
    title: 'Вычитание до 10',
    titleKk: '10-нан азайту',
    emoji: '➖',
    grade: [1],
    questions: [
      { kind: 'mc', prompt: '9 − 3 = ?', options: ['4', '5', '6', '7'], answer: '6' },
      { kind: 'mc', prompt: '8 − 5 = ?', options: ['2', '3', '4', '5'], answer: '3' },
      { kind: 'mc', prompt: '7 − 2 = ?', options: ['4', '5', '6', '7'], answer: '5' },
      { kind: 'mc', prompt: '10 − 4 = ?', options: ['5', '6', '7', '8'], answer: '6' },
      { kind: 'mc', prompt: '6 − 1 = ?', options: ['4', '5', '6', '7'], answer: '5' },
      { kind: 'mc', prompt: '9 − 9 = ?', options: ['0', '1', '2', '3'], answer: '0' },
      { kind: 'mc', prompt: '8 − 3 = ?', options: ['4', '5', '6', '7'], answer: '5' },
      { kind: 'mc', prompt: '10 − 7 = ?', options: ['1', '2', '3', '4'], answer: '3' },
    ],
  },
  {
    id: 'math-3',
    subjectId: 'math',
    title: 'Сложение до 20',
    titleKk: '20-ға дейін қосу',
    emoji: '🔢',
    grade: [1, 2],
    questions: [
      { kind: 'mc', prompt: '8 + 7 = ?', options: ['13', '14', '15', '16'], answer: '15' },
      { kind: 'mc', prompt: '9 + 6 = ?', options: ['13', '14', '15', '16'], answer: '15' },
      { kind: 'mc', prompt: '7 + 8 = ?', options: ['13', '14', '15', '16'], answer: '15' },
      { kind: 'mc', prompt: '6 + 7 = ?', options: ['11', '12', '13', '14'], answer: '13' },
      { kind: 'mc', prompt: '9 + 9 = ?', options: ['16', '17', '18', '19'], answer: '18' },
      { kind: 'mc', prompt: '8 + 5 = ?', options: ['11', '12', '13', '14'], answer: '13' },
      { kind: 'mc', prompt: '7 + 6 = ?', options: ['11', '12', '13', '14'], answer: '13' },
      { kind: 'mc', prompt: '9 + 4 = ?', options: ['11', '12', '13', '14'], answer: '13' },
    ],
  },
  {
    id: 'math-4',
    subjectId: 'math',
    title: 'Таблица умножения ×2',
    titleKk: '×2 көбейту кестесі',
    emoji: '✖️',
    grade: [2, 3],
    questions: [
      { kind: 'mc', prompt: '2 × 3 = ?', options: ['4', '5', '6', '7'], answer: '6' },
      { kind: 'mc', prompt: '2 × 5 = ?', options: ['8', '9', '10', '11'], answer: '10' },
      { kind: 'mc', prompt: '2 × 7 = ?', options: ['12', '13', '14', '15'], answer: '14' },
      { kind: 'mc', prompt: '2 × 4 = ?', options: ['6', '7', '8', '9'], answer: '8' },
      { kind: 'mc', prompt: '2 × 9 = ?', options: ['16', '17', '18', '19'], answer: '18' },
      { kind: 'mc', prompt: '2 × 6 = ?', options: ['10', '11', '12', '13'], answer: '12' },
      { kind: 'mc', prompt: '2 × 8 = ?', options: ['14', '15', '16', '17'], answer: '16' },
      { kind: 'mc', prompt: '2 × 10 = ?', options: ['18', '19', '20', '21'], answer: '20' },
    ],
  },
  {
    id: 'math-5',
    subjectId: 'math',
    title: 'Таблица умножения ×3',
    titleKk: '×3 көбейту кестесі',
    emoji: '✖️',
    grade: [2, 3],
    questions: [
      { kind: 'mc', prompt: '3 × 3 = ?', options: ['7', '8', '9', '10'], answer: '9' },
      { kind: 'mc', prompt: '3 × 4 = ?', options: ['10', '11', '12', '13'], answer: '12' },
      { kind: 'mc', prompt: '3 × 5 = ?', options: ['13', '14', '15', '16'], answer: '15' },
      { kind: 'mc', prompt: '3 × 6 = ?', options: ['16', '17', '18', '19'], answer: '18' },
      { kind: 'mc', prompt: '3 × 7 = ?', options: ['19', '20', '21', '22'], answer: '21' },
      { kind: 'mc', prompt: '3 × 8 = ?', options: ['22', '23', '24', '25'], answer: '24' },
      { kind: 'mc', prompt: '3 × 9 = ?', options: ['25', '26', '27', '28'], answer: '27' },
      { kind: 'mc', prompt: '3 × 10 = ?', options: ['28', '29', '30', '31'], answer: '30' },
    ],
  },
  {
    id: 'math-6',
    subjectId: 'math',
    title: 'Деление',
    titleKk: 'Бөлу',
    emoji: '➗',
    grade: [3, 4],
    questions: [
      { kind: 'mc', prompt: '12 ÷ 3 = ?', options: ['3', '4', '5', '6'], answer: '4' },
      { kind: 'mc', prompt: '20 ÷ 4 = ?', options: ['4', '5', '6', '7'], answer: '5' },
      { kind: 'mc', prompt: '18 ÷ 6 = ?', options: ['2', '3', '4', '5'], answer: '3' },
      { kind: 'mc', prompt: '24 ÷ 8 = ?', options: ['2', '3', '4', '5'], answer: '3' },
      { kind: 'mc', prompt: '35 ÷ 7 = ?', options: ['4', '5', '6', '7'], answer: '5' },
      { kind: 'mc', prompt: '36 ÷ 9 = ?', options: ['3', '4', '5', '6'], answer: '4' },
      { kind: 'mc', prompt: '42 ÷ 6 = ?', options: ['5', '6', '7', '8'], answer: '7' },
      { kind: 'mc', prompt: '56 ÷ 8 = ?', options: ['6', '7', '8', '9'], answer: '7' },
    ],
  },
]
